### ISSUE TITLE
Memory (Handle) Leak

### ISSUE THREAD

**Issue by maiad** [danm-de/pcsc-sharp#101]
Hallo, I am afraid, that between EstablishContext and ReleaseContext is a memory leak. Try this code 

```
            var contextFactory = ContextFactory.Instance;
            for (int i = 0; i < 10; i++)
            {
                int handlesBefore = System.Diagnostics.Process.GetCurrentProcess().HandleCount;
                using (var context = contextFactory.Establish(SCardScope.System)) { }
                int handlesAfter = System.Diagnostics.Process.GetCurrentProcess().HandleCount;
                System.Diagnostics.Debug.WriteLine("Handles leak : " + (handlesAfter - handlesBefore));
            } 
```
Do you have the same problem ?

**Comment by danm-de** [comment]
Hi @maiad ,

yes, I can confirm the problem. 

Might be the same issue as described here: https://stackoverflow.com/questions/48742884/scardestablishcontext-memory-leak

Just used [dotMemory ](https://www.jetbrains.com/dotmemory/) to profile a test application. The grey area is the unmanaged memory after 20'000 iterations:
![image](https://user-images.githubusercontent.com/3825484/82705452-f6919a00-9c77-11ea-8d28-c7dc6986cc46.png)

However, after ~45 MB it slows (~10k handles instead of the expected 20k).

**Comment by danm-de** [comment]
https://developercommunity.visualstudio.com/content/problem/522909/winscard-memory-leak-in-windows-10.html

okay...
> I did more thorough testing, and the memory can be seen to be steadily increasing in the Diagnostic Tools window for the first 5000 iterations or so, but afterwards stabilizes. [...]

> Hi Customer，I will closed the feedback as not a bug.

**Comment by danm-de** [comment]
Seems to be a Windows PC/SC related problem, cannot fix, sorry :-(
