### ISSUE TITLE
Load key failed on clean Mifare Classic 1k tag

### ISSUE THREAD

**Issue by KyryloAntoshyn** [danm-de/pcsc-sharp#102]
Hi!

I've cloned your repository and try to run Mifare1kTest example. I have Windows 10, ACR122U reader and Mifare Classic 1k tag. When I try to load key (send External Authenticate command) I always receive ’6300’ code which means that authentication failed.
![image](https://user-images.githubusercontent.com/26432700/89420357-40e4cc00-d73b-11ea-9829-68de83b616aa.png)
For this example I made factory reset of my card and checked it with Mifare Classic tool – it is empty and has default Key A and Key B. When I comment load key logic example works fine.

I also tried to run ApduTest.GET_CHALLENGE example and it says that "APDU is invalid". I tried to run it, because for external authentication this condition is needed: "The successful execution of the command requires that the last challenge obtained from the card is valid."
![image](https://user-images.githubusercontent.com/26432700/89420158-ff542100-d73a-11ea-9e33-0e5421bf8aa4.png)

I've also found this link with the same problem: https://stackoverflow.com/questions/41480611/pcsc-sharp-mifare-authentication.

Why do I have such a strange behavior and how to fix it? Thanks in advance!

**Comment by danm-de** [comment]
Hi, 

the ACR122U requires different handling when accessing RFID chips. Regarding to your posted stackoverflow article, the problem is at line 38 in Program.cs

https://github.com/danm-de/pcsc-sharp/blob/master/Examples/ISO7816-4/Mifare1kTest/Program.cs#L38

Change the statement from 

```c#
var loadKeySuccessful = card.LoadKey(
    KeyStructure.NonVolatileMemory,
    0x00, // first key slot
    new byte[] {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF} // key
);
```

to

```c#
var loadKeySuccessful = card.LoadKey(
    KeyStructure.VolatileMemory,
    0x00, // first key slot
    new byte[] {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF} // key
);
```

I assume the ACR122U hardware only has volatile memory. Actually I don't know - I do not own a ACR122U and therefore never read their [specs.](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjYs8Pm_ZDrAhXQ3KQKHQ_8DGcQFjADegQIARAB&url=https%3A%2F%2Fwww.acs.com.hk%2Fdrivers%2Feng%2FAPI-ACR122U-2.02.pdf&usg=AOvVaw3U0I1M3pd-UcAtU3XM-shi) before.

You might want to have a look at page 12.

:-)

**Comment by KyryloAntoshyn** [comment]
Yes, thanks, I understand the difference now.
