### ISSUE TITLE
Create memory card example

### ISSUE THREAD

**Issue by mika76** [danm-de/pcsc-sharp#12]
Our cards write directly to memory cards. Could you maybe post an example of how to read data directly from a memory card (index and length variable)? I am not having much luck figuring it out. The library seems to say it cannot identify card or something (I'll come back and post exact enum when I can)

**Comment by mika76** [comment]
I was trying something like this:
```
var reader = new SCardReader(context);
var rc = reader.Connect(readerNames[0], SCardShareMode.Direct, SCardProtocol.Raw);

Console.WriteLine(rc); //returns Present, Mute

var apdu = new CommandApdu(IsoCase.Case2Short, SCardProtocol.Raw)
{
    CLA = 0xFF,
    Instruction = InstructionCode.ReadBinary,
    P1 = 0x00,
    P2 = 0x00,
    Le = 0x28  // We don't know the ID tag size
};
// says IsValid but no data returned
```

I also do not know which IsoCase to use for a serial memory card?

**Comment by danm-de** [comment]
Hi Mika,

as far as I know there is no way to address memory cards by using the ISO APDUs because the hardware communication is different from normal processor cards. 

I know that several manufactures implemented "pseudo"-APDUs in their products, that will help you to access such cards - but these commands are vendor specific (-> see your card reader vendor's manual for more information) . You've defined 0xFF as class byte in your example, that means it is actually not defined by ISO 7816.

If you are using a vendor specific command - and it still does not work, you should have a look here:
https://github.com/danm-de/pcsc-sharp/pull/9
It is possible that pcsc-sharp has a bug in the IsoReader class.

Greetings,
Daniel

**Comment by danm-de** [comment]
No answer, closed.
