### ISSUE TITLE
Smart card resource manager is not running

### ISSUE THREAD

**Issue by huw-trimet** [danm-de/pcsc-sharp#24]
Hello there, tried to use your pscs-sharp package send APDU commands, when attempting to establish context call:
context.Establish(SCardScope.System);

I got the following:

[message : The Smart card resource manager is not running.] [source : pcsc-sharp] 
[stackTrace :    at PCSC.SCardErrorExtensionMethods.Throw(SCardError sc) in D:\danm\Dokumente\GitHub\pcsc-sharp\pcsc-sharp\ExtensionMethods\SCardErrorExtensionMethods.cs:line 24
   at PCSC.SCardContext.Establish(SCardScope scope) in D:\danm\Dokumente\GitHub\pcsc-sharp\pcsc-sharp\SCardContext.cs:line 58

I am connecting to a Zebra ZXP 8 printer with a SDI010 contactless encoder, on a Windows 7 OS.  My smart card is a NXP DesFire EV1 chip.  I checked all MS Windows relevant information seemed everything was set up correctly.  Please help, thanks in advance.

**Comment by danm-de** [comment]
Is the smart card service (SCardSvr) started? If you need help to start it, please have a look here: http://computerstepbystep.com/smart_card_service.html

If the service is *running* and you keep getting this error message, please check this out:
https://blogs.msdn.microsoft.com/alejacma/2011/05/19/scardestablishcontext-fails-with-scard_e_no_service-error/

You have to install a PC/SC compliant driver (or SDK) - otherwise Windows will not recognize your device.

**Comment by huw-trimet** [comment]
Hello, I assumed your wrapper library worked with Windows 7 OS, though your site stated only tested for Windows 10.  Thanks in advance.
________________________________

**Comment by danm-de** [comment]
Yes, it does work with Windows 7.

**Comment by huw-trimet** [comment]
Great, it started working now.

I need to authenticate with DesFire EV1 with AES, and write some data block to a specific AID file.

I felt your Challenge example is a good start to go, will be interested to know if you know anyone willing to do a small paid job?

Please let me know, thanks.
