### ISSUE TITLE
SCCardMonitor stops reporting Card Removed events

### ISSUE THREAD

**Issue by paulrefpoint** [danm-de/pcsc-sharp#25]
Hi,

I am using your library in a Windows 8.1 environment and have found it to be absolutely perfect for our needs.

I am having one small issue however.

If I create a SCCardMonitor and call the Start method on it I can successfully pick up Card Inserted and Card Removed events. If I subsequently call the Cancel method on the SCCardMonitor and then call the Start method again, I will see Card Inserted events but no longer see any events raised or status changes when a card is removed.  

If I call SCardContext.Release() followed by SCCardContext.ReEstablish() after I call Cancel on the SCardMonitor this seems to sort the problem but I'm not sure if this will have any unforeseen consequences.

Regards

Paul McCay

**Comment by danm-de** [comment]
Hi Paul,

I haven't seen this issue yet. Maybe, because I do not recycle `SCardMonitor` instances. (Will check later this week).

I would not recommend you to _Release_ and _ReEstablish_ an `ISCardContext` that has already been hand over to a `SCardMonitor` instance. (Even though the monitor is technically stopped by calling `ISCardContext.Cancel()`..) 

Personally, I prefer to dispose and re-create a context+monitor instead of calling _Cancel_ + _(Re)start_. How often do you do this? Once per minute, once per second, ..?

There is a new branch that could be interesting for you:
https://github.com/danm-de/pcsc-sharp/tree/feature/rx

It contains several classes to ease monitor usage. 
(e.g. https://github.com/danm-de/pcsc-sharp/blob/feature/rx/pcsc-sharp/Monitoring/MonitorFactory.cs)

A new project (PCSC.Reactive / pcsc-sharp-rx) provides observables for smart card events. 
https://github.com/danm-de/pcsc-sharp/tree/feature/rx/pcsc-sharp-rx
Examples:
- https://github.com/danm-de/pcsc-sharp/tree/feature/rx/Examples/Reactive/RxEventsTest
- https://github.com/danm-de/pcsc-sharp/tree/feature/rx/Examples/Reactive/RxEventsTestWpf

Regards,
Daniel

**Comment by paulrefpoint** [comment]
Hi Daniel,

Thank you very much for taking the time to reply.

I’ll try your alternative to Release and ReEstablish and also take a look at the other projects below.

Many Thanks

Paul

**Comment by danm-de** [comment]
Hi Paul,

I was able to reproduce your described error. Threading problem in SCardMonitor (again *sigh*). Working on a solution.

**Comment by danm-de** [comment]
Okay,
I've tried to make `SCardMonitor` more *thread-safe*. Could you check it in your application please?
https://github.com/danm-de/pcsc-sharp/tree/feature/rx

**Comment by paulrefpoint** [comment]
Brilliant thank you so much for the quick response – I’ll test that and get back to you today.

Paul

**Comment by paulrefpoint** [comment]
I've tested the new version in our code this morning and everything around the monitoring is working perfectly.

Thanks once again.

**Comment by danm-de** [comment]
Version 3.5.0 released
