### ISSUE TITLE
XP Legacy

### ISSUE THREAD

**Issue by Alex1130** [danm-de/pcsc-sharp#34]
Is it possible to use PCSC with Win XP and VS10-SP1?

Here is the reference to the pcsc-sharp Project
http://labs.a-trust.at/developer/ShowSource.aspx?id=114
Here is the C# code I'd like to use:
http://labs.a-trust.at/developer/downloads/apduExamples_0.5.zip
My current setup can not meet the following dependencies
    
    using PCSC;
    using PCSC.Iso7816;
    
If this is the wrong place to ask could you direct me to the right one?

**Comment by danm-de** [comment]
Hi Alex,

Could you please describe your problem a bit more detailed? I've just checked the .csproj file of pcsc-sharp and it says ".Net Framework 4.0" -which is the last supported version in XP. What kind of error do you get when downloading / using the NUGET package?

BTW, you can find me at the #devopenspace this weekend.

**Comment by Alex1130** [comment]
Hi Daniel, 
The difficulty I encountered was to install NUGET, as the oldest Version is labelled for VS13 (at least that's how it looked to me at first (https://dist.nuget.org/index.html)). 
In the meantime I found a link to version 2.8.6 (https://visualstudiogallery.msdn.microsoft.com/27077b70-9dad-4c64-adcf-c7cf6bc9970c) which also includes the link to a manually installable Powershell 2.0 - now I realized 2.8.6 was on the NUGET download site all along...
I will report back as soon as I tried installing these packages.

**Comment by Alex1130** [comment]
I installed  [PowerShell 2.0](https://www.microsoft.com/de-at/download/details.aspx?id=16818) .
I ran [nuget.exe (v2.8.6)](https://dist.nuget.org/win-x86-commandline/v2.8.6/nuget.exe) and the following error was raised:
```
PS C:\Programme\NuGet> .\nuget.exe
nuget.exe : Der Typ "System.Runtime.CompilerServices.ExtensionAttribute" in der Assembly "mscorlib, Version=4.0.0.
0, Culture=neutral, PublicKeyToken=b77a5c561934e089" konnte nicht geladen werden.
Bei Zeile:1 Zeichen:12
+ .\nuget.exe <<<< 
    + CategoryInfo          : NotSpecified: (Der Typ "System...geladen werden.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```
I have .NET 4.0.30319 installed - do I need to use configuration options? Or is my understanding of the combination of PowerShell and nuget.exe wrong?

**Comment by danm-de** [comment]
@Alex1130 I don't know if it is possible to install/run nuget on Windows XP (which is deprecated for 6 years and unsupported since 8th April 2014).

Try to 
1. download the (raw) nuget package here: http://www.nuget.org/api/v2/package/PCSC/3.5.1
2. rename the file extension from .nupkg to .zip
3. extract all files from lib/net40/
4. reference pcsc-sharp directly (using "Add reference" or "Verweis hinzufügen")
5. Do not forget to place the pcsc-sharp.XML in the same directory as the pcsc-sharp.dll (otherwise you won't get intellisense)

If the binary does not work, you need to - lets say - "backport" the sources by yourself. Grab the files from https://github.com/danm-de/pcsc-sharp/tree/master/pcsc-sharp and create your own solution to build the project.

@Alex1130 I really hope you're *not* intend to use Windows XP / Embedded as an operating system for cash machines.

**Comment by Alex1130** [comment]
Thanks, downloading,extracting and direct referencing worked 

(I'm trying to get a grip on APDU PCSC. Don't worry I am not using Windows since 2001 (that's why I have no newer Windows Version available) - but I thought I 'd use the demo code I got from the smartcard vendor - which has proven more challenging than I hoped it to be. The next step will be to check it out on linux )
