### ISSUE TITLE
Controlling ACR1252U NFC Reader Peripherals

### ISSUE THREAD

**Issue by Ngugi1** [danm-de/pcsc-sharp#50]
Hello, I am trying to send a command to make ACR1252U buzzer sound. I see we have the method `control(controlCode, sendbuffer , receiveBuffer)` but I can't find an example on how to use it. I would appreciate if one provided some quick sample code to deal with my issue

**Comment by danm-de** [comment]
Hi,

google for
https://www.codeproject.com/Questions/1113324/How-to-control-smart-card-readers-without-card-on
at the bottom you'll find a C# example that can be adopted.

Here is an example how to use the pcsc-sharp API in general:
https://github.com/danm-de/pcsc-sharp/blob/master/Examples/Transmit/Program.cs

**Instead** of `.BeginTransaction()` and `.Transmit(..)` you should call the `Control(IntPtr controlCode, byte[] sendBuffer, ref byte[] receiveBuffer)` method providing the appropriate reader specific buffers (see codeproject example). Please consult your vendor's _reader programming guide_ for more information (E.g. _5.8.4 Buzzer Control_).
http://www.acs.com.hk/download-manual/6402/API-ACR1252U-1.09.pdf

Unfortunately that's all information I can give you since I do not own an ACR1252U reader.

**Comment by danm-de** [comment]
Closed
