### ISSUE TITLE
Does not build in VS2015

### ISSUE THREAD

**Issue by trollcop** [danm-de/pcsc-sharp#63]
IsoReader.cs, "throw" invalid expression term
WinScardAPI.cs, several errors related to "out var"

**Comment by danielmue** [comment]
PCSC-sharp starts using C# 7.0 features. Please update your VS in order to compile the solution (https://www.visualstudio.com/).

Both compile errors are new language features, please have a look at
https://blogs.msdn.microsoft.com/dotnet/2016/08/24/whats-new-in-csharp-7-0/
https://blogs.msdn.microsoft.com/dotnet/2017/03/09/new-features-in-c-7-0/
- Out variables
- Throw expressions

**Comment by trollcop** [comment]
Ah I see.
I chose to have something that actually works, instead of using language features that nobody else wants or uses.

I have a licensed VS2015 installation and I have no interest in updating to 2017 or anything newer just to compile something that's literally a wrapper around winscard.dll
