### ISSUE TITLE
Transmit Example

### ISSUE THREAD

**Issue by foaadnami** [danm-de/pcsc-sharp#64]
When trying this example, its asks about RFID. Can this example be used to transmit APDU to a contact smart card ?

**Comment by danm-de** [comment]
Yes, the PC/SC library (API) was designed to communicate with contact chips.
See example https://github.com/danm-de/pcsc-sharp/tree/master/Examples/ISO7816-4/ApduTest.GET_CHALLENGE
that sends a GET CHALLENGE request and reads the response.

The most vendors of RFID readers provide a PC/SC complaint driver. That's why you can use the same API to send and receive data from contactless chips.
